language: generic
sudo: required
services:
    - docker
# build
before_install:
    - docker build -t "$DOCKER_ID"/react-test -f ./client/Dockerfile.dev ./client
# run tests
script:
    - docker run -e CI=true "$DOCKER_ID"/react-test npm test

after_success:
    # Login to docker CLI
    - docker login  -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
    # build production images
    - docker build -t "$DOCKER_ID"/fib-client ./client
    - docker build -t "$DOCKER_ID"/fib-nginx ./nginx
    - docker build -t "$DOCKER_ID"/fib-server ./server
    - docker build -t "$DOCKER_ID"/fib-worker ./worker
    # push images to docker-hub
    - docker push "$DOCKER_ID"/fib-client
    - docker push "$DOCKER_ID"/fib-nginx
    - docker push "$DOCKER_ID"/fib-server
    - docker push "$DOCKER_ID"/fib-worker
